### ISSUE TITLE
Using hapi plugins to version your API and perform server-side multivariate testing

### ISSUE THREAD

**Issue by dstevensio** [jsfest/2014-oakland-cfp#136]
Organizing your web application using hapi's plugin architecture provides a great deal of flexibility and modularization.

Here, I'll spend 10 minutes detailing how to utilize this flexibility to version your API and round out a further 10 minutes with the possibilities for multivariate testing on the server-side using the same flexible structure offered by plugins.

**Comment by hueniverse** [comment]
Can you squeeze all that into one 10m slot? :-)

**Comment by dstevensio** [comment]
If that's the time available, sure!

**Comment by hueniverse** [comment]
You're in.
