### ISSUE TITLE
A Community of People, Not Projects

### ISSUE THREAD

**Issue by crtr0** [jsfest/2014-oakland-cfp#31]
When I became a developer evangelist in early 2012, I was told that an important part of my job was to support my developer community. This open ended mandate was both scary and exciting and I threw myself into the role, eventually getting involved in organizing meetups, hackathons, conferences and even a coworking space in my adopted home of Seattle, WA. However, earlier this year I started to experience severe burnout related to these activities and as I spoke to other organizers I started to hear similar stories. 

This talk is about the joys of getting involved but also how the things that you love can sometimes hurt you. I’d like to share a few things I learned recently about prioritizing people over projects that make contributing both more scalable and also much more rewarding.

**Comment by mikeal** [comment]
would it be possible to combine this talk with your other proposal, I like the narrative that begins when you became and evangelist but the conclusion is something like "we don't have any of this shit written down" which is what your other proposal is about :)

**Comment by crtr0** [comment]
Sounds good to me. I'm making some progress on [writing things down](https://github.com/cascadiajs/how-to-conf) and it would be great to let people know about these resources.
