### ISSUE TITLE
Talk Proposal: Rethinking the bedrock of computing

### ISSUE THREAD

**Issue by edef1c** [jsfest/2014-oakland-cfp#58]
Computing has changed a lot in the past 50 years, but we're still programming computers like it's 1970. Especially our operating systems suffer from this, but our programming languages aren't far off either.

We've made huge advances in managing modularity, and package management has moved forward to match. In node-land, we've moved with that, even actively driven innovation in these areas. We already have extreme modularity, good ways of handling versioning, and isolating concerns.

To fully take advantage of this, and to build computer systems that embody this, we need to rethink our entire stack from the ground up. The goal is to remove as many assumptions as possible from the lowest layers of our stack, and rethink even the fundamentals of operating systems.

In this mad science modular future, nothing is sacred. Drop the filesystem, and replace it with a database — or even a decentralised block storage system! To this end I'm building an exo/microkernel called Sulphur, written in Rust.

This talk is intended for Nothing is Sacred.

/cc @brycebaril

**Comment by thefoxis** [comment]
I WANT THIS

**Comment by brycebaril** [comment]
Accepted for Nothing Is Sacred :)

**Comment by edef1c** [comment]
:sparkling_heart:

**Comment by mikeal** [comment]
If you haven't already, please register yourself as a speaker for JSFest:

https://ti.to/jsfest/oakland?release_id=nqflw0il0qw

If you get it in within the next few days you'll probably get a much nicer conference badge :)

And for any clever buggers who think they can register for free using that link, we will be checking the names against the accepted speakers list :)
