### ISSUE TITLE
On the road to diversity

### ISSUE THREAD

**Issue by hueniverse** [jsfest/2014-oakland-cfp#67]
I am not sure where this belongs, but since I already have a talk planned for hapiDay, it cannot be there.

I've set diversity as my top goal for the year. It started with diversity of companies involved in the hapi.js project as the lack of voices was slowing innovation. But what we soon discovered was that lack of more basic diversity - gender (and gender expression) - was actually a much bigger problem.

I've changed the entire project roadmap to accomplish the kind of meaningful diversity we as a community have been talking about but had little luck delivering. This included a new governance model, aggressive breakup of the framework components, conducting community interviews, recruitment of non-white-male contributors, and a mentorship program.

This talk will share what I have learned through this process, how we set to solve the issues, and why addressing diversity requires getting your hands dirty and making significant changes beyond just a code of conduct and supportive tweets.

**Comment by thefoxis** [comment]
I'm kinda digging this for Nothing is Sacred.

**Comment by hueniverse** [comment]
WFM

**Comment by mikeal** [comment]
Nothing is Sacred only has time for 4 talks. I might take this for NodeConf though.

**Comment by jessepollak** [comment]
I think this could also be a good fit for JSBBQ - nice way to prime the week?

**Comment by hueniverse** [comment]
At this point I don't have enough time to prepare. I'll find a home for this talk in the future.
