### ISSUE TITLE
Re-thinking Technical Interviewing

### ISSUE THREAD

**Issue by Moishe** [jsfest/2014-oakland-cfp#97]
# Intro

I've been interviewing lots over the last 10 years or so, and I think the process is broken and to the extent we hire good people we do it by luck, and we routinely don't hire the best people. I think this is probably a good talk for Nothing is Sacred.
# Abstract

The basic format for hiring software engineers, especially at larger companies, hasn't changed in decades: find a pool of applicants, filter the applicants by some apparatus (eg. school, experience), further filter with a phone conversation, bring candidate onsite for a day of interviews (generally whiteboard coding or otherwise solving problems that can be solved in 45 minutes or less), decide to hire based on that day's worth of data.

I'd like to talk about how to find candidates differently, how to think about what would make a great hire with constraints different than "can they write code on a whiteboard," and some practical ideas to implement new hiring systems.
# About Me

I'm an engineering manager at Etsy; I've been here for about 18 months. Before Etsy, I worked at Google as a software engineer for 7 years. I was at Microsoft and a few smaller companies before that. I lucked into writing software more or less by accident with a high school internship.

I interviewed over 250 candidates at Google, served on the hiring committee, and taught interview training workshops. My pace of interviewing has slowed dramatically here at Etsy but I've been responsible for recruiting and hiring on my team, and I've taught a handful of interview training workshops here as well.

**Comment by jessepollak** [comment]
:+1: 

If Nothing is Sacred doesn't want this, I'd love to have you in [JSBBQ](http://oakland.jsbbq.org/).

**Comment by Moishe** [comment]
JSBBQ could be great! Might be a stretch schedule-wise (I'm in Nashville on Dec. 6th) but let's see what happens with Nothing is Sacred.

**Comment by Moishe** [comment]
Argh, just found out that I need to be in Brooklyn this week and won't be able to make it to Oakland for this. Withdrawing my entry by closing this issue. HUGE apologies! Hope to do it next time around.

**Comment by jessepollak** [comment]
:( next time!
